POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "My First Post",
    "slug": "my-first-post",
    "content": "This is the content of my first post.",
    "tags": ["introduction", "welcome"],
    "postType": "post",
    "postStatus": "draft",
    "publishOn": "2024-10-01T10:00:00Z",
    "metaOption": {
        "metaValue": {
            "sidebarEnabled": true,
            "theme": "dark"
        }
    }
}